pytest:
    image: python:latest

    before_script:
        - python3 --version
        - pip3 --version  # for debugging
        - pip3 install -r requirements.txt

    script:
        - python3 -m pytest --verbosity=2
