name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test-miex:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: python3 --version
      - run: pip3 --version  # for debugging
      - run: pip3 install -r requirements.txt
      - run: python3 -m pytest --verbosity=2
